// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzNdUVcut_g4QEVte12V_tJ72ALvrHxug',
    appId: '1:766708933702:web:c572763b1196abe3e01647',
    messagingSenderId: '766708933702',
    projectId: 'chat-app-7febf',
    authDomain: 'chat-app-7febf.firebaseapp.com',
    storageBucket: 'chat-app-7febf.appspot.com',
    measurementId: 'G-7TD3YSLB0D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjPI4OoGpS3a0MH4X-4OdwXF_1lu3BVZQ',
    appId: '1:766708933702:android:e172a7036dd47e43e01647',
    messagingSenderId: '766708933702',
    projectId: 'chat-app-7febf',
    storageBucket: 'chat-app-7febf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAmBKjqBAISH-gl-k6p3iI-NWkMQDcNoU',
    appId: '1:766708933702:ios:3543b626760a80a4e01647',
    messagingSenderId: '766708933702',
    projectId: 'chat-app-7febf',
    storageBucket: 'chat-app-7febf.appspot.com',
    iosBundleId: 'com.example.chatSetupApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAmBKjqBAISH-gl-k6p3iI-NWkMQDcNoU',
    appId: '1:766708933702:ios:b0c04c9c7d05cff8e01647',
    messagingSenderId: '766708933702',
    projectId: 'chat-app-7febf',
    storageBucket: 'chat-app-7febf.appspot.com',
    iosBundleId: 'com.example.chatSetupApp.RunnerTests',
  );
}
